### ISSUE TITLE
iOS 7, _videoOutput in sharedSetup causes crash during capture with torch mode on

### ISSUE THREAD

**Issue by aaronpeterson** [sridenour/SRCameraView#1]
_videoOutput being added to _captureSession seems to be triggering a possible iOS 7 bug that will cause captureStillImageAsynchronouslyFromConnection to hang.

Thought I'd let anyone know who is using SRCameraView.  Hoping to send some pull requests soon :)

**Comment by sridenour** [comment]
Strange...

**Comment by sridenour** [comment]
Is anyone still having this issue? The example app works fine if you add
`[self.cameraView setCurrentCameraFlashMode:AVCaptureFlashModeOn];` somewhere after the camera view has been initialized.

**Comment by sridenour** [comment]
Or did you mean if you actually just go and turn the flash on permanently?
